---
title: "Large-scale data analysis in R"
author: Peter Carbonetto
output:
  beamer_presentation:
    template: docs/beamer.tex
    keep_tex: false
    fig_caption: false
    pandoc_args: "--highlight-style=pygments"
---

```{r knitr-options, echo=FALSE}
knitr::opts_chunk$set(results = "hide",fig.show = "hide",
                      message = FALSE,warning = FALSE)
```

Workshop aims
=============

1. Develop skills for large-scale data analyis in R, and apply these
skills to a large-ish data set.

2. Learn how to use R **non-interactively** within a high-performance
computing (HPC) environment.

3. Assess memory needs, and make good use of it.

4. Speeding up your R analyses by...

    + Using simple parallelization techniques.

    + Interfacing to C code.

5. Learn through **live coding**---this includes learning from our
mistakes!

It's your choice
================

You may choose to...

+ Use R on the RCC cluster.

+ Use R on your laptop.

+ Pair up with your neighbour.

+ Follow what I do on the projector.

Please note:

+ You should use R, not RStudio.
 
+ Some of the examples will not work on your laptop.

Outline of workshop
===================

*Add outline here.*

The RegMap data set
===================

+ Genetic and climate data on *Arabidopsis thaliana.*

+ From Joy Bergelson's lab at the University of Chicago.

+ See [Hancock et al (2011) *Science* 334, 83--86][hancock-2011].

[hancock-2011]: http://dx.doi.org/10.1126/science.1209244 
